### ISSUE TITLE
Gradle Build CMake Error.

### ISSUE THREAD

**Issue by ozMod** [sfalexrog/Imgui_Android#4]
I downloaded your project and opened in Android Studio.
Then i tried to just sync gradle. I got the following error:
`Cause: executing external native build for cmake C:\Imgui_Android-master\ImguiDemoSdl\src\main\cpp\CMakeLists.txt`
![image](https://user-images.githubusercontent.com/80401984/131719931-c021a803-457b-4a42-99a2-08cd22045f5c.png)
I just want to test that project on my.
What i needs to do?)

**Comment by ozMod** [comment]
I'm understand that i doesnt have sdl2 but how can i do it

**Comment by sfalexrog** [comment]
I believe you haven't initialized the submodules (you need to run `git submodule update --init --recursive` in the source checkout), but I haven't touched the sources in a while, so there might be some bit rot.

Maybe it's time to update the project again!
